# tasks file for network-utils
- name: Raw update cache with fix missing
  raw: apt update --fix-missing
- name: Install apt-https transport
  action: apt name=apt-transport-https state=present 
- name: Install packages
  with_items: "{{ network.packages }}"
  apt:
    package: "{{ item }}"
    update_cache: yes
    state: present