---
# tasks file for docker
- name: Add docker apt keys
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Update apt repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main' state=present

- name: Install Docker package
  apt: pkg=docker-engine=1.13.1-0~debian-jessie update_cache=yes
